apiVersion: v1
kind: Service
metadata:
  name: {{ include "link-shortener-js.fullname" . }}
  labels:
    {{- include "link-shortener-js.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $val := .Values.ports }}
    - name: {{ $val.name | quote }}
      port: {{ $val.number }}
    {{- end }}
  selector:
    {{- include "link-shortener-js.selectorLabels" . | nindent 4 }}
